export const dataListBanks = [
  {
    bank_code: "050",
    bank_name: "STANDARD CHARTERED BANK",
    code: "STANDARD_CHARTERED",
    id: 0,
    name: "STANDARD CHARTERED BANK",
    swift_code: "SCBLIDJX",
  },
  {
    bank_code: "L52",
    bank_name: "PT. BANK RBS",
    code: "RBS",
    id: 1,
    name: "PT. BANK RBS",
    swift_code: "ABNAIDJA",
  },
  {
    bank_code: "520",
    bank_name: "PT. PRIMA MASTER BANK",
    code: "PRIMA_MASTER",
    id: 2,
    name: "PT. PRIMA MASTER BANK",
    swift_code: "PMASIDJ1",
  },
  {
    bank_code: "OVO",
    bank_name: "OVO (PT Visionet Internasional)",
    code: "EWALLET_OVO",
    id: 3,
    name: "OVO (PT Visionet Internasional)",
    swift_code: "OVO",
  },
  {
    bank_code: "564",
    bank_name: "PT. BANK MANDIRI TASPEN POS",
    code: "MANDIRI_TASPEN",
    id: 4,
    name: "PT. BANK MANDIRI TASPEN POS",
    swift_code: "SIHBIDJ1",
  },
  {
    bank_code: "032",
    bank_name: "JP MORGAN CHASE BANK, N.A",
    code: "JPMORGAN",
    id: 5,
    name: "JP MORGAN CHASE BANK, N.A",
    swift_code: "CHASIDJX",
  },
  {
    bank_code: "003",
    bank_name: "BANK EKSPOR INDONESIA",
    code: "EXIMBANK",
    id: 6,
    name: "BANK EKSPOR INDONESIA",
    swift_code: "LPEIIDJ1",
  },
  {
    bank_code: "087",
    bank_name: "HONGKONG AND SHANGHAI BANK CORPORATION",
    code: "HSBC",
    id: 7,
    name: "HONGKONG AND SHANGHAI BANK CORPORATION",
    swift_code: "HSBCIDJA",
  },
  {
    bank_code: "087",
    bank_name: "HONGKONG AND SHANGHAI BANK CORPORATION. UUS",
    code: "HSBC_UUS",
    id: 8,
    name: "HONGKONG AND SHANGHAI BANK CORPORATION. UUS",
    swift_code: "HSBCIDJA",
  },
  {
    bank_code: "GOPAY",
    bank_name: "GOPAY (PT Aplikasi Karya Anak Bangsa)",
    code: "EWALLET_GOPAY",
    id: 9,
    name: "GOPAY (PT Aplikasi Karya Anak Bangsa)",
    swift_code: "GOPAY",
  },
  {
    bank_code: "067",
    bank_name: "DEUTSCHE BANK AG",
    code: "DEUTSCHE",
    id: 10,
    name: "DEUTSCHE BANK AG",
    swift_code: "DEUTIDJA",
  },
  {
    bank_code: "DANA",
    bank_name: "DANA (PT. Espay Debit Indonesia)",
    code: "EWALLET_DANA",
    id: 11,
    name: "DANA (PT. Espay Debit Indonesia)",
    swift_code: "DANA",
  },
  {
    bank_code: "031",
    bank_name: "CITIBANK N.A.",
    code: "CITIBANK",
    id: 12,
    name: "CITIBANK N.A.",
    swift_code: "CITIIDJX",
  },
  {
    bank_code: "036",
    bank_name: "PT BANK CHINA CONSTRUCTION BANK INDONESIA, TBK.",
    code: "CCB",
    id: 13,
    name: "PT BANK CHINA CONSTRUCTION BANK INDONESIA, TBK.",
    swift_code: "BWKIIDJA",
  },
  {
    bank_code: "559",
    bank_name: "PT. CENTRATAMA NASIONAL BANK",
    code: "CENTRATAMA",
    id: 14,
    name: "PT. CENTRATAMA NASIONAL BANK",
    swift_code: "CNBAIDJ1",
  },
  {
    bank_code: "547",
    bank_name: "PT. BANK BTPN SYARIAH, TBK.",
    code: "BTPN_SYARIAH",
    id: 15,
    name: "PT. BANK BTPN SYARIAH, TBK.",
    swift_code: "PUBAIDJ1",
  },
  {
    bank_code: "117",
    bank_name: "PT. BPD SUMUT. UUS",
    code: "SUMUT_UUS",
    id: 16,
    name: "PT. BPD SUMUT. UUS",
    swift_code: "SYSUIDJ1",
  },
  {
    bank_code: "117",
    bank_name: "PT. BPD SUMUT",
    code: "SUMUT",
    id: 17,
    name: "PT. BPD SUMUT",
    swift_code: "PDSUIDJ1",
  },
  {
    bank_code: "120",
    bank_name: "PT. BPD SUMSEL DAN BABEL. UUS",
    code: "SUMSEL_DAN_BABEL_UUS",
    id: 18,
    name: "PT. BPD SUMSEL DAN BABEL. UUS",
    swift_code: "SYSSIDJ1",
  },
  {
    bank_code: "120",
    bank_name: "PT. BPD SUMSEL DAN BABEL",
    code: "SUMSEL_DAN_BABEL",
    id: 19,
    name: "PT. BPD SUMSEL DAN BABEL",
    swift_code: "BSSPIDSP",
  },
  {
    bank_code: "118",
    bank_name: "PT. BPD SUMATERA BARAT. UUS",
    code: "SUMATERA_BARAT_UUS",
    id: 20,
    name: "PT. BPD SUMATERA BARAT. UUS",
    swift_code: "SYSBIDJ1",
  },
  {
    bank_code: "118",
    bank_name: "PT. BPD SUMATERA BARAT",
    code: "SUMATERA_BARAT",
    id: 21,
    name: "PT. BPD SUMATERA BARAT",
    swift_code: "PDSBIDSP",
  },
  {
    bank_code: "127",
    bank_name: "PT. BPD SULUT",
    code: "SULUT",
    id: 22,
    name: "PT. BPD SULUT",
    swift_code: "PDWUIDJ1",
  },
  {
    bank_code: "126",
    bank_name: "PT. BPD SULSELBAR. UUS",
    code: "SULSELBAR_UUS",
    id: 23,
    name: "PT. BPD SULSELBAR. UUS",
    swift_code: "SYWSIDJ1",
  },
  {
    bank_code: "126",
    bank_name: "PT. BPD SULSELBAR",
    code: "SULSELBAR",
    id: 24,
    name: "PT. BPD SULSELBAR",
    swift_code: "PDWSIDJ1",
  },
  {
    bank_code: "135",
    bank_name: "PT. BPD SULAWESI TENGGARA",
    code: "SULAWESI_TENGGARA",
    id: 25,
    name: "PT. BPD SULAWESI TENGGARA",
    swift_code: "PDWRIDJ1",
  },
  {
    bank_code: "134",
    bank_name: "PT. BPD SULAWESI TENGAH",
    code: "SULAWESI",
    id: 26,
    name: "PT. BPD SULAWESI TENGAH",
    swift_code: "PDWGIDJ1",
  },
  {
    bank_code: "119",
    bank_name: "PT. BPD RIAU DAN KEPRI. UUS",
    code: "RIAU_DAN_KEPRI_UUS",
    id: 27,
    name: "PT. BPD RIAU DAN KEPRI. UUS",
    swift_code: "SYRIIDJ1",
  },
  {
    bank_code: "119",
    bank_name: "PT. BPD RIAU DAN KEPRI",
    code: "RIAU_DAN_KEPRI",
    id: 28,
    name: "PT. BPD RIAU DAN KEPRI",
    swift_code: "PDRIIDJA",
  },
  {
    bank_code: "132",
    bank_name: "PT. BPD PAPUA",
    code: "PAPUA",
    id: 29,
    name: "PT. BPD PAPUA",
    swift_code: "PDIJIDJ1",
  },
  {
    bank_code: "130",
    bank_name: "PT. BPD NUSA TENGGARA TIMUR",
    code: "NUSA_TENGGARA_TIMUR",
    id: 30,
    name: "PT. BPD NUSA TENGGARA TIMUR",
    swift_code: "PDNTIDJ1",
  },
  {
    bank_code: "128",
    bank_name: "PT. BPD NUSA TENGGARA BARAT. UUS",
    code: "NUSA_TENGGARA_BARAT_UUS",
    id: 31,
    name: "PT. BPD NUSA TENGGARA BARAT. UUS",
    swift_code: "SYNBIDJ1",
  },
  {
    bank_code: "128",
    bank_name: "PT. BPD NUSA TENGGARA BARAT",
    code: "NUSA_TENGGARA_BARAT",
    id: 32,
    name: "PT. BPD NUSA TENGGARA BARAT",
    swift_code: "PDNBIDJ1",
  },
  {
    bank_code: "131",
    bank_name: "PT. BPD MALUKU",
    code: "MALUKU",
    id: 33,
    name: "PT. BPD MALUKU",
    swift_code: "PDMLIDJ1",
  },
  {
    bank_code: "121",
    bank_name: "PT. BPD LAMPUNG",
    code: "LAMPUNG",
    id: 34,
    name: "PT. BPD LAMPUNG",
    swift_code: "PDLPIDJ1",
  },
  {
    bank_code: "124",
    bank_name: "PT. BPD KALIMANTAN TIMUR. UUS",
    code: "KALIMANTAN_TIMUR_UUS",
    id: 35,
    name: "PT. BPD KALIMANTAN TIMUR. UUS",
    swift_code: "SYKTIDJ1",
  },
  {
    bank_code: "124",
    bank_name: "PT. BPD KALIMANTAN TIMUR",
    code: "KALIMANTAN_TIMUR",
    id: 36,
    name: "PT. BPD KALIMANTAN TIMUR",
    swift_code: "PDKTIDJ1",
  },
  {
    bank_code: "125",
    bank_name: "PT. BPD KALIMANTAN TENGAH",
    code: "KALIMANTAN_TENGAH",
    id: 37,
    name: "PT. BPD KALIMANTAN TENGAH",
    swift_code: "PDKGIDJ1",
  },
  {
    bank_code: "122",
    bank_name: "PT. BPD KALIMANTAN SELATAN. UUS",
    code: "KALIMANTAN_SELATAN_UUS",
    id: 38,
    name: "PT. BPD KALIMANTAN SELATAN. UUS",
    swift_code: "SYKSIDJ1",
  },
  {
    bank_code: "122",
    bank_name: "PT. BPD KALIMANTAN SELATAN",
    code: "KALIMANTAN_SELATAN",
    id: 39,
    name: "PT. BPD KALIMANTAN SELATAN",
    swift_code: "PDKSIDJ1",
  },
  {
    bank_code: "123",
    bank_name: "PT. BPD KALIMANTAN BARAT. UUS",
    code: "KALIMANTAN_BARAT_UUS",
    id: 40,
    name: "PT. BPD KALIMANTAN BARAT. UUS",
    swift_code: "SYKBIDJ1",
  },
  {
    bank_code: "123",
    bank_name: "PT. BPD KALIMANTAN BARAT",
    code: "KALIMANTAN_BARAT",
    id: 41,
    name: "PT. BPD KALIMANTAN BARAT",
    swift_code: "PDKBIDJ1",
  },
  {
    bank_code: "114",
    bank_name: "PT. BPD JAWA TIMUR. UUS",
    code: "JAWA_TIMUR_UUS",
    id: 42,
    name: "PT. BPD JAWA TIMUR. UUS",
    swift_code: "SYJTIDJ1",
  },
  {
    bank_code: "114",
    bank_name: "PT. BPD JAWA TIMUR",
    code: "JAWA_TIMUR",
    id: 43,
    name: "PT. BPD JAWA TIMUR",
    swift_code: "PDJTIDJ1",
  },
  {
    bank_code: "113",
    bank_name: "PT. BPD JAWA TENGAH. UUS",
    code: "JAWA_TENGAH_UUS",
    id: 44,
    name: "PT. BPD JAWA TENGAH. UUS",
    swift_code: "SYJGIDJ1",
  },
  {
    bank_code: "113",
    bank_name: "PT. BPD JAWA TENGAH",
    code: "JAWA_TENGAH",
    id: 45,
    name: "PT. BPD JAWA TENGAH",
    swift_code: "PDJGIDJ1",
  },
  {
    bank_code: "115",
    bank_name: "PT. BPD JAMBI. UUS",
    code: "JAMBI_UUS",
    id: 46,
    name: "PT. BPD JAMBI. UUS",
    swift_code: "SYJMIDJ1",
  },
  {
    bank_code: "115",
    bank_name: "PT. BPD JAMBI",
    code: "JAMBI",
    id: 47,
    name: "PT. BPD JAMBI",
    swift_code: "PDJMIDJ1",
  },
  {
    bank_code: "112",
    bank_name: "PT. BPD DAERAH ISTIMEWA YOGYAKARTA. UUS",
    code: "DAERAH_ISTIMEWA_UUS",
    id: 48,
    name: "PT. BPD DAERAH ISTIMEWA YOGYAKARTA. UUS",
    swift_code: "SYYKIDJ1",
  },
  {
    bank_code: "112",
    bank_name: "PT. BPD DAERAH ISTIMEWA YOGYAKARTA",
    code: "DAERAH_ISTIMEWA",
    id: 49,
    name: "PT. BPD DAERAH ISTIMEWA YOGYAKARTA",
    swift_code: "PDYKIDJ1",
  },
  {
    bank_code: "133",
    bank_name: "PT. BPD BENGKULU",
    code: "BENGKULU",
    id: 50,
    name: "PT. BPD BENGKULU",
    swift_code: "PDBKIDJ1",
  },
  {
    bank_code: "137",
    bank_name: "PT. BANK PEMBANGUNAN DAERAH BANTEN",
    code: "BANTEN",
    id: 51,
    name: "PT. BANK PEMBANGUNAN DAERAH BANTEN",
    swift_code: "PDBBIDJ1",
  },
  {
    bank_code: "129",
    bank_name: "PT. BPD BALI",
    code: "BALI",
    id: 52,
    name: "PT. BPD BALI",
    swift_code: "ABALIDBS",
  },
  {
    bank_code: "116",
    bank_name: "PT. BPD ACEH. UUS",
    code: "ACEH_UUS",
    id: 53,
    name: "PT. BPD ACEH. UUS",
    swift_code: "SYACIDJ1",
  },
  {
    bank_code: "116",
    bank_name: "PT. BPD ACEH",
    code: "ACEH",
    id: 54,
    name: "PT. BPD ACEH",
    swift_code: "PDACIDJ1",
  },
  {
    bank_code: "490",
    bank_name: "PT. BANK YUDHA BHAKTI",
    code: "YUDHA_BHAKTI",
    id: 55,
    name: "PT. BANK YUDHA BHAKTI",
    swift_code: "YUDBIDJ1",
  },
  {
    bank_code: "212",
    bank_name: "PT. BANK WOORI SAUDARA INDONESIA 1906, TBK",
    code: "WOORI_SAUDARA",
    id: 56,
    name: "PT. BANK WOORI SAUDARA INDONESIA 1906, TBK",
    swift_code: "HVBKIDJA",
  },
  {
    bank_code: "068",
    bank_name: "PT. BANK WOORI SAUDARA ,TBK.",
    code: "WOORI",
    id: 57,
    name: "PT. BANK WOORI SAUDARA ,TBK.",
    swift_code: "HVBKIDJA",
  },
  {
    bank_code: "405",
    bank_name: "PT. BANK VICTORIA SYARIAH",
    code: "VICTORIA_SYR",
    id: 58,
    name: "PT. BANK VICTORIA SYARIAH",
    swift_code: "SWAGIDJ1",
  },
  {
    bank_code: "566",
    bank_name: "PT. BANK VICTORIA INTERNASIONAL",
    code: "VICTORIA_INTERNASIONAL",
    id: 59,
    name: "PT. BANK VICTORIA INTERNASIONAL",
    swift_code: "BVICIDJA",
  },
  {
    bank_code: "023",
    bank_name: "PT. BANK UOB INDONESIA",
    code: "UOB",
    id: 60,
    name: "PT. BANK UOB INDONESIA",
    swift_code: "BBIJIDJA",
  },
  {
    bank_code: "213",
    bank_name: "PT. BANK TABUNGAN PENSIUNAN NASIONAL",
    code: "TABUNGAN_PENSIUNAN_NASIONAL",
    id: 61,
    name: "PT. BANK TABUNGAN PENSIUNAN NASIONAL",
    swift_code: "BTPNIDJA",
  },
  {
    bank_code: "200",
    bank_name: "PT. BANK TABUNGAN NEGARA, TBK. UUS",
    code: "BTN_UUS",
    id: 62,
    name: "PT. BANK TABUNGAN NEGARA, TBK. UUS",
    swift_code: "SYBTIDJ1",
  },
  {
    bank_code: "200",
    bank_name: "PT. BANK TABUNGAN NEGARA, TBK.",
    code: "BTN",
    id: 63,
    name: "PT. BANK TABUNGAN NEGARA, TBK.",
    swift_code: "BTANIDJA",
  },
  {
    bank_code: "506",
    bank_name: "PT. BANK SYARIAH MEGA INDONESIA",
    code: "MEGA_SYR",
    id: 64,
    name: "PT. BANK SYARIAH MEGA INDONESIA",
    swift_code: "BUTGIDJ1",
  },
  {
    bank_code: "451",
    bank_name: "PT. BANK SYARIAH MANDIRI",
    code: "MANDIRI_SYR",
    id: 65,
    name: "PT. BANK SYARIAH MANDIRI",
    swift_code: "BSMDIDJA",
  },
  {
    bank_code: "521",
    bank_name: "PT. BANK SYARIAH BUKOPIN",
    code: "BUKOPIN_SYR",
    id: 66,
    name: "PT. BANK SYARIAH BUKOPIN",
    swift_code: "SDOBIDJ1",
  },
  {
    bank_code: "422",
    bank_name: "PT. BANK SYARIAH BRI",
    code: "BRI_SYR",
    id: 67,
    name: "PT. BANK SYARIAH BRI",
    swift_code: "DJARIDJ1",
  },
  {
    bank_code: "045",
    bank_name: "PT. BANK SUMITOMO MITSUI INDONESIA",
    code: "MITSUI",
    id: 68,
    name: "PT. BANK SUMITOMO MITSUI INDONESIA",
    swift_code: "SUNIIDJA",
  },
  {
    bank_code: "734",
    bank_name: "PT. BANK SINARMAS UNIT USAHA SYARIAH",
    code: "SINARMAS_UUS",
    id: 69,
    name: "PT. BANK SINARMAS UNIT USAHA SYARIAH",
    swift_code: "SYTBIDJ1",
  },
  {
    bank_code: "153",
    bank_name: "PT. BANK SINARMAS",
    code: "SINARMAS",
    id: 70,
    name: "PT. BANK SINARMAS",
    swift_code: "SBJKIDJA",
  },
  {
    bank_code: "152",
    bank_name: "PT. BANK SHINHAN INDONESIA",
    code: "SHINHAN",
    id: 71,
    name: "PT. BANK SHINHAN INDONESIA",
    swift_code: "MEEKIDJ1",
  },
  {
    bank_code: "498",
    bank_name: "PT. BANK SBI INDONESIA",
    code: "SBI_INDONESIA",
    id: 72,
    name: "PT. BANK SBI INDONESIA",
    swift_code: "IDMOIDJ1",
  },
  {
    bank_code: "523",
    bank_name: "PT. BANK SAHABAT SAMPOERNA",
    code: "SAHABAT_SAMPOERNA",
    id: 73,
    name: "PT. BANK SAHABAT SAMPOERNA",
    swift_code: "BDIPIDJ1",
  },
  {
    bank_code: "501",
    bank_name: "PT. BANK ROYAL INDONESIA",
    code: "ROYAL",
    id: 74,
    name: "PT. BANK ROYAL INDONESIA",
    swift_code: "ROYBIDJ1",
  },
  {
    bank_code: "047",
    bank_name: "PT. BANK RESONA PERDANIA",
    code: "RESONA",
    id: 75,
    name: "PT. BANK RESONA PERDANIA",
    swift_code: "BPIAIDJA",
  },
  {
    bank_code: "002",
    bank_name: "PT. BANK RAKYAT INDONESIA, TBK.",
    code: "BRI",
    id: 76,
    name: "PT. BANK RAKYAT INDONESIA, TBK.",
    swift_code: "BRINIDJA",
  },
  {
    bank_code: "089",
    bank_name: "PT. BANK RABOBANK INTERNATIONAL INDONESIA",
    code: "RABOBANK",
    id: 77,
    name: "PT. BANK RABOBANK INTERNATIONAL INDONESIA",
    swift_code: "RABOIDJA",
  },
  {
    bank_code: "167",
    bank_name: "PT. BANK QNB INDONESIA",
    code: "QNB_INDONESIA",
    id: 78,
    name: "PT. BANK QNB INDONESIA",
    swift_code: "AWANIDJA",
  },
  {
    bank_code: "013",
    bank_name: "PT. BANK PERMATA, TBK. UUS",
    code: "PERMATA_UUS",
    id: 79,
    name: "PT. BANK PERMATA, TBK. UUS",
    swift_code: "SYBBIDJ1",
  },
  {
    bank_code: "013",
    bank_name: "PT. BANK PERMATA, TBK.",
    code: "PERMATA",
    id: 80,
    name: "PT. BANK PERMATA, TBK.",
    swift_code: "BBBAIDJA",
  },
  {
    bank_code: "517",
    bank_name: "PT. BANK PANIN DUBAI SYARIAH",
    code: "PANIN_SYR",
    id: 81,
    name: "PT. BANK PANIN DUBAI SYARIAH",
    swift_code: "ARFAIDJ1",
  },
  {
    bank_code: "019",
    bank_name: "PT. BANK PANIN",
    code: "PANIN",
    id: 82,
    name: "PT. BANK PANIN",
    swift_code: "PINBIDJA",
  },
  {
    bank_code: "466",
    bank_name: "PT. BANK OKE INDONESIA",
    code: "OKE",
    id: 83,
    name: "PT. BANK OKE INDONESIA",
    swift_code: "RIPAIDJ1",
  },
  {
    bank_code: "042",
    bank_name: "BANK OF TOKYO MITSUBISHI UFJ, LTD.",
    code: "TOKYO",
    id: 84,
    name: "BANK OF TOKYO MITSUBISHI UFJ, LTD.",
    swift_code: "BOTKIDJX",
  },
  {
    bank_code: "146",
    bank_name: "PT. BANK INDIA",
    code: "INDIA",
    id: 85,
    name: "PT. BANK INDIA",
    swift_code: "BKIDIDJA",
  },
  {
    bank_code: "069",
    bank_name: "BANK OF CHINA LIMITED",
    code: "BOC",
    id: 86,
    name: "BANK OF CHINA LIMITED",
    swift_code: "BKCHIDJA",
  },
  {
    bank_code: "033",
    bank_name: "BANK OF AMERICA MERRILL-LYNCH",
    code: "BAML",
    id: 87,
    name: "BANK OF AMERICA MERRILL-LYNCH",
    swift_code: "BOFAID2X",
  },
  {
    bank_code: "028",
    bank_name: "PT. BANK OCBC NISP, TBK. UUS",
    code: "OCBC_UUS",
    id: 88,
    name: "PT. BANK OCBC NISP, TBK. UUS",
    swift_code: "SYONIDJ1",
  },
  {
    bank_code: "028",
    bank_name: "PT. BANK OCBC NISP, TBK.",
    code: "OCBC",
    id: 89,
    name: "PT. BANK OCBC NISP, TBK.",
    swift_code: "NISPIDJA",
  },
  {
    bank_code: "145",
    bank_name: "PT. BANK NUSANTARA PARAHYANGAN",
    code: "NUSANTARA_PARAHYANGAN",
    id: 90,
    name: "PT. BANK NUSANTARA PARAHYANGAN",
    swift_code: "NUPAIDJ6",
  },
  {
    bank_code: "009",
    bank_name: "PT. BANK NEGARA INDONESIA, TBK.",
    code: "BNI",
    id: 91,
    name: "PT. BANK NEGARA INDONESIA, TBK.",
    swift_code: "BNINIDJA",
  },
  {
    bank_code: "503",
    bank_name: "BANK NATIONALNOBU",
    code: "NATIONALNOBU",
    id: 92,
    name: "BANK NATIONALNOBU",
    swift_code: "LFIBIDJ1",
  },
  {
    bank_code: "548",
    bank_name: "PT. BANK MULTI ARTA SENTOSA",
    code: "MULTI_ARTA_SENTOSA",
    id: 93,
    name: "PT. BANK MULTI ARTA SENTOSA",
    swift_code: "BMSEIDJA",
  },
  {
    bank_code: "147",
    bank_name: "PT. BANK MUAMALAT INDONESIA TBK",
    code: "MUAMALAT",
    id: 94,
    name: "PT. BANK MUAMALAT INDONESIA TBK",
    swift_code: "MUABIDJA",
  },
  {
    bank_code: "485",
    bank_name: "PT. BANK MNC INTERNASIONAL, TBK.",
    code: "MNC_INTERNASIONAL",
    id: 95,
    name: "PT. BANK MNC INTERNASIONAL, TBK.",
    swift_code: "BUMIIDJA",
  },
  {
    bank_code: "048",
    bank_name: "PT. BANK MIZUHO INDONESIA",
    code: "MIZUHO",
    id: 96,
    name: "PT. BANK MIZUHO INDONESIA",
    swift_code: "MHCCIDJA",
  },
  {
    bank_code: "491",
    bank_name: "PT. BANK MITRA NIAGA",
    code: "MITRA_NIAGA",
    id: 97,
    name: "PT. BANK MITRA NIAGA",
    swift_code: "MGABIDJ1",
  },
  {
    bank_code: "151",
    bank_name: "PT. BANK MESTIKA DHARMA",
    code: "MESTIKA_DHARMA",
    id: 98,
    name: "PT. BANK MESTIKA DHARMA",
    swift_code: "MEDHIDS1",
  },
  {
    bank_code: "426",
    bank_name: "PT. BANK MEGA, TBK.",
    code: "MEGA",
    id: 99,
    name: "PT. BANK MEGA, TBK.",
    swift_code: "MEGAIDJA",
  },
  {
    bank_code: "553",
    bank_name: "PT. BANK MAYORA",
    code: "MAYORA",
    id: 100,
    name: "PT. BANK MAYORA",
    swift_code: "MAYOIDJA",
  },
  {
    bank_code: "016",
    bank_name: "PT. BANK MAYBANK INDONESIA SYRIAH TBK.",
    code: "MAYBANK_SYR",
    id: 101,
    name: "PT. BANK MAYBANK INDONESIA SYRIAH TBK.",
    swift_code: "MBBEIDJA",
  },
  {
    bank_code: "016",
    bank_name: "PT. BANK MAYBANK INDONESIA TBK.",
    code: "MAYBANK",
    id: 102,
    name: "PT. BANK MAYBANK INDONESIA TBK.",
    swift_code: "IBBKIDJA",
  },
  {
    bank_code: "097",
    bank_name: "PT. BANK MAYAPADA INTERNATIONAL, TBK.",
    code: "MAYAPADA",
    id: 103,
    name: "PT. BANK MAYAPADA INTERNATIONAL, TBK.",
    swift_code: "MAYAIDJA",
  },
  {
    bank_code: "157",
    bank_name: "PT. BANK MASPION INDONESIA",
    code: "MASPION",
    id: 104,
    name: "PT. BANK MASPION INDONESIA",
    swift_code: "MASDIDJS",
  },
  {
    bank_code: "008",
    bank_name: "PT. BANK MANDIRI, TBK.",
    code: "MANDIRI",
    id: 105,
    name: "PT. BANK MANDIRI, TBK.",
    swift_code: "BMRIIDJA",
  },
  {
    bank_code: "535",
    bank_name: "PT. BANK KESEJAHTERAAN EKONOMI",
    code: "KESEJAHTERAAN_EKONOMI",
    id: 106,
    name: "PT. BANK KESEJAHTERAAN EKONOMI",
    swift_code: "KSEBIDJ1",
  },
  {
    bank_code: "095",
    bank_name: "PT. BANK J TRUST INDONESIA, TBK.",
    code: "JTRUST",
    id: 107,
    name: "PT. BANK J TRUST INDONESIA, TBK.",
    swift_code: "CICTIDJA",
  },
  {
    bank_code: "472",
    bank_name: "PT. BANK JASA JAKARTA",
    code: "JASA_JAKARTA",
    id: 108,
    name: "PT. BANK JASA JAKARTA",
    swift_code: "JAJSIDJ1",
  },
  {
    bank_code: "555",
    bank_name: "PT. BANK INDEX SELINDO",
    code: "INDEX_SELINDO",
    id: 109,
    name: "PT. BANK INDEX SELINDO",
    swift_code: "BIDXIDJA",
  },
  {
    bank_code: "513",
    bank_name: "PT. BANK INA PERDANA",
    code: "INA_PERDANA",
    id: 110,
    name: "PT. BANK INA PERDANA",
    swift_code: "INPBIDJ1",
  },
  {
    bank_code: "164",
    bank_name: "PT. BANK ICBC INDONESIA",
    code: "ICBC",
    id: 111,
    name: "PT. BANK ICBC INDONESIA",
    swift_code: "ICBKIDJA",
  },
  {
    bank_code: "212",
    bank_name: "BANK HIMPUNAN SAUDARA 1906, TBK",
    code: "HIMPUNAN_SAUDARA",
    id: 112,
    name: "BANK HIMPUNAN SAUDARA 1906, TBK",
    swift_code: "HVBKIDJA",
  },
  {
    bank_code: "567",
    bank_name: "PT. BANK HARDA INTERNASIONAL",
    code: "HARDA_INTERNASIONAL",
    id: 113,
    name: "PT. BANK HARDA INTERNASIONAL",
    swift_code: "HRDAIDJ1",
  },
  {
    bank_code: "484",
    bank_name: "PT. BANK HANA",
    code: "HANA",
    id: 114,
    name: "PT. BANK HANA",
    swift_code: "HNBNIDJA",
  },
  {
    bank_code: "161",
    bank_name: "PT. BANK GANESHA",
    code: "GANESHA",
    id: 115,
    name: "PT. BANK GANESHA",
    swift_code: "GNESIDJA",
  },
  {
    bank_code: "562",
    bank_name: "PT. BANK FAMA INTERNATIONAL",
    code: "FAMA",
    id: 116,
    name: "PT. BANK FAMA INTERNATIONAL",
    swift_code: "FAMAIDJ1",
  },
  {
    bank_code: "111",
    bank_name: "PT. BANK DKI. UUS",
    code: "DKI_UUS",
    id: 117,
    name: "PT. BANK DKI. UUS",
    swift_code: "SYDKIDJ1",
  },
  {
    bank_code: "111",
    bank_name: "PT. BANK DKI",
    code: "DKI",
    id: 118,
    name: "PT. BANK DKI",
    swift_code: "BDKIIDJA",
  },
  {
    bank_code: "526",
    bank_name: "PT. BANK DINAR INDONESIA",
    code: "DINAR_INDONESIA",
    id: 119,
    name: "PT. BANK DINAR INDONESIA",
    swift_code: "LMANIDJ1",
  },
  {
    bank_code: "046",
    bank_name: "PT. BANK DBS INDONESIA",
    code: "DBS",
    id: 120,
    name: "PT. BANK DBS INDONESIA",
    swift_code: "DBSBIDJA",
  },
  {
    bank_code: "011",
    bank_name: "PT. BANK DANAMON INDONESIA, TBK. UUS",
    code: "DANAMON_UUS",
    id: 121,
    name: "PT. BANK DANAMON INDONESIA, TBK. UUS",
    swift_code: "SYBDIDJ1",
  },
  {
    bank_code: "011",
    bank_name: "PT. BANK DANAMON INDONESIA, TBK.",
    code: "DANAMON",
    id: 122,
    name: "PT. BANK DANAMON INDONESIA, TBK.",
    swift_code: "BDINIDJA",
  },
  {
    bank_code: "950",
    bank_name: "PT. BANK COMMONWEALTH",
    code: "COMMONWEALTH",
    id: 123,
    name: "PT. BANK COMMONWEALTH",
    swift_code: "BICNIDJA",
  },
  {
    bank_code: "022",
    bank_name: "PT. BANK CIMB NIAGA, TBK. UUS",
    code: "CIMB_UUS",
    id: 124,
    name: "PT. BANK CIMB NIAGA, TBK. UUS",
    swift_code: "SYNAIDJ1",
  },
  {
    bank_code: "022",
    bank_name: "PT. BANK CIMB NIAGA, TBK",
    code: "CIMB",
    id: 125,
    name: "PT. BANK CIMB NIAGA, TBK",
    swift_code: "BNIAIDJA",
  },
  {
    bank_code: "949",
    bank_name: "PT. BANK CHINATRUST INDONESIA",
    code: "CHINATRUST",
    id: 126,
    name: "PT. BANK CHINATRUST INDONESIA",
    swift_code: "CTCBIDJA",
  },
  {
    bank_code: "536",
    bank_name: "PT. BANK BCA SYARIAH",
    code: "BCA_SYR",
    id: 127,
    name: "PT. BANK BCA SYARIAH",
    swift_code: "SYCAIDJ1",
  },
  {
    bank_code: "014",
    bank_name: "PT. BANK CENTRAL ASIA, TBK.",
    code: "BCA",
    id: 128,
    name: "PT. BANK CENTRAL ASIA, TBK.",
    swift_code: "CENAIDJA",
  },
  {
    bank_code: "054",
    bank_name: "PT. BANK CAPITAL INDONESIA",
    code: "CAPITAL",
    id: 129,
    name: "PT. BANK CAPITAL INDONESIA",
    swift_code: "BCIAIDJA",
  },
  {
    bank_code: "076",
    bank_name: "PT. BANK BUMI ARTA",
    code: "BUMI_ARTA",
    id: 130,
    name: "PT. BANK BUMI ARTA",
    swift_code: "BBAIIDJA",
  },
  {
    bank_code: "441",
    bank_name: "PT. BANK BUKOPIN",
    code: "BUKOPIN",
    id: 131,
    name: "PT. BANK BUKOPIN",
    swift_code: "BBUKIDJA",
  },
  {
    bank_code: "494",
    bank_name: "PT. BANK BRI AGRONIAGA TBK.",
    code: "AGRONIAGA",
    id: 132,
    name: "PT. BANK BRI AGRONIAGA TBK.",
    swift_code: "AGTBIDJA",
  },
  {
    bank_code: "057",
    bank_name: "PT. BANK BNP PARIBAS INDONESIA",
    code: "BNP_PARIBAS",
    id: 133,
    name: "PT. BANK BNP PARIBAS INDONESIA",
    swift_code: "BNPAIDJA",
  },
  {
    bank_code: "427",
    bank_name: "PT. BANK BNI SYARIAH",
    code: "BNI_SYR",
    id: 134,
    name: "PT. BANK BNI SYARIAH",
    swift_code: "SYNIIDJ1",
  },
  {
    bank_code: "425",
    bank_name: "PT. BANK BJB SYARIAH",
    code: "BJB_SYR",
    id: 135,
    name: "PT. BANK BJB SYARIAH",
    swift_code: "SYJBIDJ1",
  },
  {
    bank_code: "110",
    bank_name: "PT. BANK BJB",
    code: "BJB",
    id: 136,
    name: "PT. BANK BJB",
    swift_code: "PDJBIDJA",
  },
  {
    bank_code: "459",
    bank_name: "PT. BANK BISNIS INTERNASIONAL",
    code: "BISNIS_INTERNASIONAL",
    id: 137,
    name: "PT. BANK BISNIS INTERNASIONAL",
    swift_code: "BUSTIDJ1",
  },
  {
    bank_code: "542",
    bank_name: "PT. BANK ARTOS INDONESIA",
    code: "ARTOS",
    id: 138,
    name: "PT. BANK ARTOS INDONESIA",
    swift_code: "ATOSIDJ1",
  },
  {
    bank_code: "037",
    bank_name: "PT. BANK ARTHA GRAHA INTERNATIONAL, TBK.",
    code: "ARTHA",
    id: 139,
    name: "PT. BANK ARTHA GRAHA INTERNATIONAL, TBK.",
    swift_code: "ARTGIDJA",
  },
  {
    bank_code: "020",
    bank_name: "BANK ARTA NIAGA KENCANA",
    code: "ARTA_NIAGA_KENCANA",
    id: 140,
    name: "BANK ARTA NIAGA KENCANA",
    swift_code: "ARNKIDJ1",
  },
  {
    bank_code: "061",
    bank_name: "PT. BANK ANZ INDONESIA",
    code: "ANZ",
    id: 141,
    name: "PT. BANK ANZ INDONESIA",
    swift_code: "ANZBIDJX",
  },
  {
    bank_code: "466",
    bank_name: "PT. BANK ANDARA",
    code: "ANDARA",
    id: 142,
    name: "PT. BANK ANDARA",
    swift_code: "RIPAIDJ1",
  },
  {
    bank_code: "531",
    bank_name: "PT. BANK AMAR INDONESIA",
    code: "AMAR",
    id: 143,
    name: "PT. BANK AMAR INDONESIA",
    swift_code: "LOMAIDJ1",
  },
  {
    bank_code: "945",
    bank_name: "PT. BANK AGRIS",
    code: "AGRIS",
    id: 144,
    name: "PT. BANK AGRIS",
    swift_code: "AGSSIDJA",
  },
  {
    bank_code: "040",
    bank_name: "BANGKOK BANK PUBLIC CO. LTD.",
    code: "BANGKOK",
    id: 145,
    name: "BANGKOK BANK PUBLIC CO. LTD.",
    swift_code: "BKKBIDJA",
  },
  {
    bank_code: "531",
    bank_name: "PT. ANGLOMAS INTERNATIONAL BANK",
    code: "ANGLOMAS",
    id: 146,
    name: "PT. ANGLOMAS INTERNATIONAL BANK",
    swift_code: "LOMAIDJ1",
  },
];

export const dataListBank = [
  { label: "STANDARD CHARTERED BANK", value: "0" },
  { label: "PT. BANK RBS", value: "1" },
  { label: "PT. PRIMA MASTER BANK", value: "2" },
  { label: "OVO (PT Visionet Internasional)", value: "3" },
  { label: "PT. BANK MANDIRI TASPEN POS", value: "4" },
  { label: "JP MORGAN CHASE BANK, N.A", value: "5" },
  { label: "BANK EKSPOR INDONESIA", value: "6" },
  { label: "HONGKONG AND SHANGHAI BANK CORPORATION", value: "7" },
  { label: "HONGKONG AND SHANGHAI BANK CORPORATION. UUS", value: "8" },
  { label: "GOPAY (PT Aplikasi Karya Anak Bangsa)", value: "9" },
  { label: "DEUTSCHE BANK AG", value: "10" },
  { label: "DANA (PT. Espay Debit Indonesia)", value: "11" },
  { label: "CITIBANK N.A.", value: "12" },
  { label: "PT BANK CHINA CONSTRUCTION BANK INDONESIA, TBK.", value: "13" },
  { label: "PT. CENTRATAMA NASIONAL BANK", value: "14" },
  { label: "PT. BANK BTPN SYARIAH, TBK.", value: "15" },
  { label: "PT. BPD SUMUT. UUS", value: "16" },
  { label: "PT. BPD SUMUT", value: "17" },
  { label: "PT. BPD SUMSEL DAN BABEL. UUS", value: "18" },
  { label: "PT. BPD SUMSEL DAN BABEL", value: "19" },
  { label: "PT. BPD SUMATERA BARAT. UUS", value: "20" },
  { label: "PT. BPD SUMATERA BARAT", value: "21" },
  { label: "PT. BPD SULUT", value: "22" },
  { label: "PT. BPD SULSELBAR. UUS", value: "23" },
  { label: "PT. BPD SULSELBAR", value: "24" },
  { label: "PT. BPD SULAWESI TENGGARA", value: "25" },
  { label: "PT. BPD SULAWESI TENGAH", value: "26" },
  { label: "PT. BPD RIAU DAN KEPRI. UUS", value: "27" },
  { label: "PT. BPD RIAU DAN KEPRI", value: "28" },
  { label: "PT. BPD PAPUA", value: "29" },
  { label: "PT. BPD NUSA TENGGARA TIMUR", value: "30" },
  { label: "PT. BPD NUSA TENGGARA BARAT. UUS", value: "31" },
  { label: "PT. BPD NUSA TENGGARA BARAT", value: "32" },
  { label: "PT. BPD MALUKU", value: "33" },
  { label: "PT. BPD LAMPUNG", value: "34" },
  { label: "PT. BPD KALIMANTAN TIMUR. UUS", value: "35" },
  { label: "PT. BPD KALIMANTAN TIMUR", value: "36" },
  { label: "PT. BPD KALIMANTAN TENGAH", value: "37" },
  { label: "PT. BPD KALIMANTAN SELATAN. UUS", value: "38" },
  { label: "PT. BPD KALIMANTAN SELATAN", value: "39" },
  { label: "PT. BPD KALIMANTAN BARAT. UUS", value: "40" },
  { label: "PT. BPD KALIMANTAN BARAT", value: "41" },
  { label: "PT. BPD JAWA TIMUR. UUS", value: "42" },
  { label: "PT. BPD JAWA TIMUR", value: "43" },
  { label: "PT. BPD JAWA TENGAH. UUS", value: "44" },
  { label: "PT. BPD JAWA TENGAH", value: "45" },
  { label: "PT. BPD JAMBI. UUS", value: "46" },
  { label: "PT. BPD JAMBI", value: "47" },
  { label: "PT. BPD DAERAH ISTIMEWA YOGYAKARTA. UUS", value: "48" },
  { label: "PT. BPD DAERAH ISTIMEWA YOGYAKARTA", value: "49" },
  { label: "PT. BPD BENGKULU", value: "50" },
  { label: "PT. BANK PEMBANGUNAN DAERAH BANTEN", value: "51" },
  { label: "PT. BPD BALI", value: "52" },
  { label: "PT. BPD ACEH. UUS", value: "53" },
  { label: "PT. BPD ACEH", value: "54" },
  { label: "PT. BANK YUDHA BHAKTI", value: "55" },
  { label: "PT. BANK WOORI SAUDARA INDONESIA 1906, TBK", value: "56" },
  { label: "PT. BANK WOORI SAUDARA ,TBK.", value: "57" },
  { label: "PT. BANK VICTORIA SYARIAH", value: "58" },
  { label: "PT. BANK VICTORIA INTERNASIONAL", value: "59" },
  { label: "PT. BANK UOB INDONESIA", value: "60" },
  { label: "PT. BANK TABUNGAN PENSIUNAN NASIONAL", value: "61" },
  { label: "PT. BANK TABUNGAN NEGARA, TBK. UUS", value: "62" },
  { label: "PT. BANK TABUNGAN NEGARA, TBK.", value: "63" },
  { label: "PT. BANK SYARIAH MEGA INDONESIA", value: "64" },
  { label: "PT. BANK SYARIAH MANDIRI", value: "65" },
  { label: "PT. BANK SYARIAH BUKOPIN", value: "66" },
  { label: "PT. BANK SYARIAH BRI", value: "67" },
  { label: "PT. BANK SUMITOMO MITSUI INDONESIA", value: "68" },
  { label: "PT. BANK SINARMAS UNIT USAHA SYARIAH", value: "69" },
  { label: "PT. BANK SINARMAS", value: "70" },
  { label: "PT. BANK SHINHAN INDONESIA", value: "71" },
  { label: "PT. BANK SBI INDONESIA", value: "72" },
  { label: "PT. BANK SAHABAT SAMPOERNA", value: "73" },
  { label: "PT. BANK ROYAL INDONESIA", value: "74" },
  { label: "PT. BANK RESONA PERDANIA", value: "75" },
  { label: "PT. BANK RAKYAT INDONESIA, TBK.", value: "76" },
  { label: "PT. BANK RABOBANK INTERNATIONAL INDONESIA", value: "77" },
  { label: "PT. BANK QNB INDONESIA", value: "78" },
  { label: "PT. BANK PERMATA, TBK. UUS", value: "79" },
  { label: "PT. BANK PERMATA, TBK.", value: "80" },
  { label: "PT. BANK PANIN DUBAI SYARIAH", value: "81" },
  { label: "PT. BANK PANIN", value: "82" },
  { label: "PT. BANK OKE INDONESIA", value: "83" },
  { label: "BANK OF TOKYO MITSUBISHI UFJ, LTD.", value: "84" },
  { label: "PT. BANK INDIA", value: "85" },
  { label: "BANK OF CHINA LIMITED", value: "86" },
  { label: "BANK OF AMERICA MERRILL-LYNCH", value: "87" },
  { label: "PT. BANK OCBC NISP, TBK. UUS", value: "88" },
  { label: "PT. BANK OCBC NISP, TBK.", value: "89" },
  { label: "PT. BANK NUSANTARA PARAHYANGAN", value: "90" },
  { label: "PT. BANK NEGARA INDONESIA, TBK.", value: "91" },
  { label: "BANK NATIONALNOBU", value: "92" },
  { label: "PT. BANK MULTI ARTA SENTOSA", value: "93" },
  { label: "PT. BANK MUAMALAT INDONESIA TBK", value: "94" },
  { label: "PT. BANK MNC INTERNASIONAL, TBK.", value: "95" },
  { label: "PT. BANK MIZUHO INDONESIA", value: "96" },
  { label: "PT. BANK MITRA NIAGA", value: "97" },
  { label: "PT. BANK MESTIKA DHARMA", value: "98" },
  { label: "PT. BANK MEGA, TBK.", value: "99" },
  { label: "PT. BANK MAYORA", value: "100" },
  { label: "PT. BANK MAYBANK INDONESIA SYRIAH TBK.", value: "101" },
  { label: "PT. BANK MAYBANK INDONESIA TBK.", value: "102" },
  { label: "PT. BANK MAYAPADA INTERNATIONAL, TBK.", value: "103" },
  { label: "PT. BANK MASPION INDONESIA", value: "104" },
  { label: "PT. BANK MANDIRI, TBK.", value: "105" },
  { label: "PT. BANK KESEJAHTERAAN EKONOMI", value: "106" },
  { label: "PT. BANK J TRUST INDONESIA, TBK.", value: "107" },
  { label: "PT. BANK JASA JAKARTA", value: "108" },
  { label: "PT. BANK INDEX SELINDO", value: "109" },
  { label: "PT. BANK INA PERDANA", value: "110" },
  { label: "PT. BANK ICBC INDONESIA", value: "111" },
  { label: "BANK HIMPUNAN SAUDARA 1906, TBK", value: "112" },
  { label: "PT. BANK HARDA INTERNASIONAL", value: "113" },
  { label: "PT. BANK HANA", value: "114" },
  { label: "PT. BANK GANESHA", value: "115" },
  { label: "PT. BANK FAMA INTERNATIONAL", value: "116" },
  { label: "PT. BANK DKI. UUS", value: "117" },
  { label: "PT. BANK DKI", value: "118" },
  { label: "PT. BANK DINAR INDONESIA", value: "119" },
  { label: "PT. BANK DBS INDONESIA", value: "120" },
  { label: "PT. BANK DANAMON INDONESIA, TBK. UUS", value: "121" },
  { label: "PT. BANK DANAMON INDONESIA, TBK.", value: "122" },
  { label: "PT. BANK COMMONWEALTH", value: "123" },
  { label: "PT. BANK CIMB NIAGA, TBK. UUS", value: "124" },
  { label: "PT. BANK CIMB NIAGA, TBK", value: "125" },
  { label: "PT. BANK CHINATRUST INDONESIA", value: "126" },
  { label: "PT. BANK BCA SYARIAH", value: "127" },
  { label: "PT. BANK CENTRAL ASIA, TBK.", value: "128" },
  { label: "PT. BANK CAPITAL INDONESIA", value: "129" },
  { label: "PT. BANK BUMI ARTA", value: "130" },
  { label: "PT. BANK BUKOPIN", value: "131" },
  { label: "PT. BANK BRI AGRONIAGA TBK.", value: "132" },
  { label: "PT. BANK BNP PARIBAS INDONESIA", value: "133" },
  { label: "PT. BANK BNI SYARIAH", value: "134" },
  { label: "PT. BANK BJB SYARIAH", value: "135" },
  { label: "PT. BANK BJB", value: "136" },
  { label: "PT. BANK BISNIS INTERNASIONAL", value: "137" },
  { label: "PT. BANK ARTOS INDONESIA", value: "138" },
  { label: "PT. BANK ARTHA GRAHA INTERNATIONAL, TBK.", value: "139" },
  { label: "BANK ARTA NIAGA KENCANA", value: "140" },
  { label: "PT. BANK ANZ INDONESIA", value: "141" },
  { label: "PT. BANK ANDARA", value: "142" },
  { label: "PT. BANK AMAR INDONESIA", value: "143" },
  { label: "PT. BANK AGRIS", value: "144" },
  { label: "BANGKOK BANK PUBLIC CO. LTD.", value: "145" },
  { label: "PT. ANGLOMAS INTERNATIONAL BANK", value: "146" },
];
